version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    networks:
      - registry
    volumes:
      - nexus-data:/nexus-data
    environment:
      # Just a small heap tune for lab use
      INSTALL4J_ADD_VM_PARAMS: -Xms512m -Xmx2048m

networks:
  registry:
    external: true

volumes:
  nexus-data:
